services:
#  web:
#    build:
#      context: .
#      target: final
#    env_file:
#      - .env
#    networks:
#      - nginx_network
#      - postgres_network
#      - redis_network
#
#  nginx:
#    image: nginx
#    restart: always
#    volumes:
#      - ./files/nginx/conf.d:/etc/nginx/conf.d
#    ports:
#      - "8080:80"
#    depends_on:
#      - web
#    networks:
#      - nginx_network

  postgres:
    image: postgres
    restart: always
    command: postgres -c 'max_connections=2000'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=cryo
      - POSTGRES_DB=cryo
    networks:
      - postgres_network

#  redis:
#    image: 'bitnami/redis:latest'
#    environment:
#      - REDIS_PASSWORD=redis123
#    volumes:
#      - redis_data:/bitnami/redis/data
#    networks:
#      - redis_network

networks:
#  nginx_network:
#    driver: bridge
  postgres_network:
    driver: bridge
#  redis_network:
#    driver: bridge

volumes:
    postgres_data:
#    redis_data:
