services:
  nginx:
    ports:
      - ${NGINX_PORT}:80

  postgres:
    environment:
      - POSTGRES_PASSWORD=example
    ports:
      - ${POSTGRES_PORT}:5432

  redis:
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PASSWORD=redis123
    ports:
      - ${REDIS_PORT}:6379

  pg-backup:
    environment:
      - POSTGRES_PASSWORD=example
