services:
  nginx:
    ports:
      - ${NGINX_PORT}:80

  postgres:
    ports:
      - ${POSTGRES_PORT}:5432

  redis:
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - ${REDIS_PORT}:6379
