services:
  api:
    build:
      context: api
      target: final
    restart: always
    env_file:
      - api/.env
    volumes:
      - ./api/data:/opt/data
    networks:
      - nginx_network
      - postgres_network
      - redis_network

  web:
    build:
      context: web
      target: final
      args:
        - BASE_API_URL=/api
        - PROJECT_NAME=MyApp
        - CONTACTS={"email":"foo@bar.baz","telegram":"foo","linkedin":"foo"}
        - SEND_MESSAGE_URL=https://example.com
        - PROJECT_GITHUB_URL=https://github.com/foo/bar
    restart: always
    environment:
      NODE_ENV: production
    networks:
      - nginx_network

  nginx:
    image: nginx:1.27.2
    restart: always
    volumes:
      - ./files/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8080:80"
    depends_on:
      - web
    networks:
      - nginx_network

  postgres:
    image: postgres:17.0
    restart: always
    command: postgres -c 'max_connections=2000'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=cryo
      - POSTGRES_DB=cryo
    networks:
      - postgres_network

  redis:
    image: 'bitnami/redis:7.4.1'
    environment:
      - REDIS_PASSWORD=redis123
    volumes:
      - redis_data:/bitnami/redis/data
    networks:
      - redis_network

networks:
  nginx_network:
    driver: bridge
  postgres_network:
    driver: bridge
  redis_network:
    driver: bridge

volumes:
    postgres_data:
    redis_data:
