CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE invoice (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  amount DECIMAL(16, 6) NOT NULL,
  seller VARCHAR(255) NOT NULL,
  buyer VARCHAR(255),
  paid_at TIMESTAMP
);
